name: hack_talk
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.4
  internet_connection_checker_plus: ^2.1.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  record: ^5.0.1
  permission_handler: ^11.0.1
  record_mp3: ^3.0.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  contained_tab_bar_view: ^0.8.0
  flutter_screenutil: ^5.9.0
  flutter_switch: ^0.3.2
  animated_splash_screen: ^1.3.0
  pretty_dio_logger: ^1.3.1
  pinput: ^4.0.0
  video_player: ^2.8.6
  data_table_2: ^2.5.15
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

